### ISSUE TITLE
Error: XML-RPC fault: Traceback 

### ISSUE THREAD

**Issue by tkharishankar** [faisalsami/odoo-xmlrpc#10]
Here my code,

const express = require('express')
const Odoo = require('../controllers/index');  //exact index what you have in github.

const app = express();  

            const odoo = new Odoo({
                url: 'http://sample.us',
                port: '8090',
                db: 'v2',
                username: 'api_user',
                password: 'api_user'
             });
            console.log('Connected to Odoo server.odoo'+odoo);  

            odoo.connect(function (err,val) {
                if (err) { return console.log(err); }
                console.log('Connected to Odoo server.');  
                console.log('Connected Result: ', value);
  
                var inParams = [];
                inParams.push('v2');
                inParams.push('232'); 
                inParams.push('qa_test_1'); 
                var params = [];
                params.push(inParams);
                odoo.execute_kw('mena.api', 'save_registration_driver', params, function (err, value) {
                    if (err) { return console.log(err); }
                    console.log('Result: ', value);
                });

            });

Facing this isssue

{ Error: XML-RPC fault: Traceback (most recent call last):
  File "/home/openerp/openerp/service/wsgi_server.py", line 84, in xmlrpc_return
    result = openerp.netsvc.dispatch_rpc(service, method, params)
  File "/home/openerp/openerp/netsvc.py", line 292, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/home/openerp/openerp/netsvc.py", line 117, in getService
    return cls._services[name]
KeyError: '2/common'

    at createFault (/Users/Hari/Documents/fetchr-codes/legacy-dt-bff/node_modules/xmlrpc/lib/deserializer.js:83:21)
    at Deserializer.onDone (/Users/Hari/Documents/fetchr-codes/legacy-dt-bff/node_modules/xmlrpc/lib/deserializer.js:89:21)
    at SAXStream.emit (events.js:160:13)
    at SAXParser.SAXStream._parser.onend (/Users/Hari/Documents/fetchr-codes/legacy-dt-bff/node_modules/sax/lib/sax.js:190:10)
    at emit (/Users/Hari/Documents/fetchr-codes/legacy-dt-bff/node_modules/sax/lib/sax.js:624:35)
    at end (/Users/Hari/Documents/fetchr-codes/legacy-dt-bff/node_modules/sax/lib/sax.js:667:5)
    at SAXParser.end (/Users/Hari/Documents/fetchr-codes/legacy-dt-bff/node_modules/sax/lib/sax.js:154:24)
    at SAXStream.end (/Users/Hari/Documents/fetchr-codes/legacy-dt-bff/node_modules/sax/lib/sax.js:248:18)
    at IncomingMessage.onend (_stream_readable.js:602:10)
    at Object.onceWrapper (events.js:255:19)
  code: '2/common',
  faultCode: '2/common',
  faultString: 'Traceback (most recent call last):\n  File "/home/openerp/openerp/service/wsgi_server.py", line 84, in xmlrpc_return\n    result = openerp.netsvc.dispatch_rpc(service, method, params)\n  File "/home/openerp/openerp/netsvc.py", line 292, in dispatch_rpc\n    result = ExportService.getService(service_name).dispatch(method, params)\n  File "/home/openerp/openerp/netsvc.py", line 117, in getService\n    return cls._services[name]\nKeyError: \'2/common\'\n' }

**Comment by faisalsami** [comment]
This error comes from odoo server so you need to probably look into that.

**Comment by stela-zheku** [comment]
Do you have any idea what should be the  problem at odoo ?

**Comment by Amin-Cheribet** [comment]
@stela-zheku the problem is not with Odoo it's with this library, this livrary has a fixed default path: '/xmlrpc/2/common',
to fix this problem you have to modify the library code and change the path manualy.

**Comment by AshokNaik009** [comment]
@Amin-Cheribet  Which file of the package needs to be updated in order to resolve this issue @faisalsami

**Comment by Amin-Cheribet** [comment]
> @Amin-Cheribet  Which file of the package needs to be updated in order to resolve this issue @faisalsami 

I can't really remember anything about this 😔,
It's been a long time ago.
