### ISSUE TITLE
Cookie challenge with odoo 17

### ISSUE THREAD

**Issue by ruti-se** [faisalsami/odoo-xmlrpc#28]
Hi,

While getting this to work successfully vs odoo 15, I am encountering the following when trying to connect to odoo 17.

It seems that the odoo server tries to retreive a cookie "td_id" which of course should not exist when logging in the first time. It is most likely a bug in odoo, but are there any provisionings for cookies in this implementation? Should it be added?

Kind regards,
Lars

Failed login using adapter odoo:XML-RPC fault: Traceback (most recent call last):
  File "/home/odoo/src/odoo/17.0/odoo/addons/base/controllers/rpc.py", line 150, in xmlrpc_2
    response = self._xmlrpc(service)
  File "/home/odoo/src/custom/trial/saas_trial/controllers/main.py", line 302, in _xmlrpc
    res = super(OdooRPC, self)._xmlrpc(service)
  File "/home/odoo/src/odoo/17.0/odoo/addons/base/controllers/rpc.py", line 130, in _xmlrpc
    result = dispatch_rpc(service, method, params)
  File "/home/odoo/src/odoo/17.0/odoo/http.py", line 388, in dispatch_rpc
    return dispatch(method, params)
  File "/home/odoo/src/odoo/17.0/odoo/service/common.py", line 56, in dispatch
    return g[exp_method_name](*params)
  File "/home/odoo/src/odoo/17.0/odoo/service/common.py", line 27, in exp_authenticate
    return res_users.authenticate(db, login, password, {**user_agent_env, 'interactive': False})
  File "/home/odoo/src/odoo/17.0/addons/auth_signup/models/res_users.py", line 129, in authenticate
    if env.user._should_alert_new_device():
  File "/home/odoo/src/odoo/17.0/addons/auth_totp/models/res_users.py", line 52, in _should_alert_new_device
    key = request.httprequest.cookies.get('td_id')
  File "/usr/lib/python3/dist-packages/werkzeug/local.py", line 432, in __get__
    obj = instance._get_current_object()
  File "/usr/lib/python3/dist-packages/werkzeug/local.py", line 554, in _get_current_object
    return self.__local()  # type: ignore
  File "/usr/lib/python3/dist-packages/werkzeug/local.py", line 226, in _lookup
    raise RuntimeError("object unbound")

**Comment by ruti-se** [comment]
However, in contradiction with the odoo manual, turning off the 2-factor authentification will enable the api to work. I leave this issue here for others to see but I close it.

**Comment by ruti-se** [comment]
Additional note - this issue was solved in odoo: https://github.com/odoo/documentation/issues/6919
