### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:80

### ISSUE THREAD

**Issue by kanrio** [faisalsami/odoo-xmlrpc#7]
This error happened when I upgraded to 1.0.6, I thought my pramaters were wrong but they are working !

```
var odoo = new Odoo({
  url: 'x.y.z.com',
  port: 80,
  db: 'Data_Base',
  username: 'username',
  password: 'pass'
});
```
ERROR : 
`{ Error: connect ECONNREFUSED 127.0.0.1:80
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 80 }`

So i downgraded to 1.0.5 and it worked again  any ideas about this ?

**EDIT :** 

I changed my URL to https and it worked but still have an other error
```
{ Error: write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:797:

    at exports._errnoException (util.js:1020:11)
    at WriteWrap.afterWrite (net.js:800:14) code: 'EPROTO', errno: 'EPROTO', syscall: 'write' }
```

**Comment by dansanti** [comment]
you must use http://url or https://url

**Comment by kanrio** [comment]
yes true, i found the solution and forget to update the issue thank you for passing by, im closing the issue

**Comment by dtnguyen-ai** [comment]
Hello!

I encountered the same problem.
Did you find solution for this error?
`{ Error: write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:797:

    at exports._errnoException (util.js:1020:11)
    at WriteWrap.afterWrite (net.js:800:14) code: 'EPROTO', errno: 'EPROTO', syscall: 'write' }`

Thank you!
